# Workflow that builds docker image and pushes it to DockerHub.
# Container from the image, executes flask application
# FLASK_DEBUG=False by default
name: Workflow that builds docker image and pushes it to DockerHub.

on:
  push:
    branches:
      - "master"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@f75d088332b07a08afadf6ac53c74509b9453f12
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push docker image to DockerHub.
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/flask_app$